### ISSUE TITLE
TS-WoW crashing after extended up time. 

### ISSUE THREAD

**Issue by kaytotes** [tswow/tswow#416]
**Is your feature request related to a problem? Please describe.**
Essentially I have a PTR that is supposed to be running 24/7. I've noticed that after 5-7 days the TS-WoW process just exits and seems to somehow take the shell with it. 

I noticed this with 0.12 too so must be an old bug. 

The last thing in logs is as follows.

```
[20:59:02][authserver]: 
[21:29:02][authserver]: Ping MySQL to keep connection alive
[21:29:02][authserver]: 
[21:36:07][realm/project-epoch.development]: [31mProcess error code 3221225786[0m
```

I used the Windows Terminal (the new one not cmd.exe) to spin up `npm run start`. It seems that even that process has exited rather than just the tswow instance crashing and shell remaining open. I will spin up using a different shell (PowerShell) this time to test and report back in a week or so. 

As best as I can tell on my PTR i started the ts-wow instance at 15/12/21 21:30 based on when the last dbc was extracted. 

It closed at 21/12/21 21:36 so almost exactly 1 week.

Nothing in `Crashes` dir to inspect

**Comment by ihm-tswow** [comment]
3221225786 is a weird error to get, because it suggests the process has been closed by ctrl+c. Since the entire window closes with it, maybe it's an issue with the terminal?

I will be able to test this on linux when we start working on that, and i'll see if I can set up a windows host with it as well to try it out on a few different terminals.

**Comment by kaytotes** [comment]
I am 99% sure this has been resolved and wasn't a TS-WoW thing specifically.
