### ISSUE TITLE
Module Profiles

### ISSUE THREAD

**Issue by tswow-admin** [tswow/tswow#6]
Allow users to organize modules into profiles that can be loaded and unloaded, allowing for loading gamemodes and similar.

**Comment by ihm-tswow** [comment]
Suggestion: Mod profiles, realms, .yaml config files and idx.txt files are all the same thing

This would make it **much** simpler conceptually both to implement for us and to manage for users.

## Config Files

Have paths like: 

- `config/default/config.yaml` + `config/default/ids.txt`
- `config/profile2/config.yaml` + `config/profile2/ids.txt`

## Modules
Should not use subdirectories, just selectively build modules with `build all` commands etc.

## Game data
We still only really need a single source database, but target databases would need to be different. I guess instead of allowing users to choose a name, we could just enforce a name that's like _tswow_world_myprofile, _tswow_auth, _tswow_characters_myprofile etc.

**Source** data (dbc_source, luaxml_source) wouldn't need to be separate, but the targets would.

## Default profile

The **default** profile should always build every module and have its own 

## Global Config

There should still be a global `tswow.yaml` to keep track of how to startup and what profiles to use etc. Maybe we can place that in the root directory instead?

**Comment by ihm-tswow** [comment]
Also think we should name the concept "realms" instead of "profiles" so users know immediately what we're talking about.
