### ISSUE TITLE
datascripts: Time taken benchmarking / tracking / debugging

### ISSUE THREAD

**Issue by kaytotes** [tswow/tswow#839]
Basically over the past month or so it feels like our large module is once again taking a loooong time to build datascripts even with --readonly. However we haven't pulled from upstream in a while so my current feeling is that something in our module is super unoptimised in how it reads / writes.

It would be handy to be able to get some kind of execution time taken for a datascript or the DB queries that end up running with time taken in ms. Even if just dumped out to a text file I could then find which queries are taking a while and infer which datascript.

**Comment by ihm-tswow** [comment]
We've tried to implement this in the past by hijacking the `require` function, but it caused some kind of issues that I forgot exactly what it was. Essentially needs to keep track of a stack of files for where to count time taken, since datascripts themselves often invoke each others before the actual loader gets to them. This would give you the time spent in the root scope of each script, which is probably what you want.

You currently have the `--profile-scripts` flag that will do a _naive_ version of this that _doesn't_ take scripts loading other scripts into account, but it might give you a hint for root files importing other files and the like. You can also trigger nodes builtin profiler by specifying `--profile`, but i've found it's rarely useful for these purposes.

**Comment by kaytotes** [comment]
The baked in --profile-scripts has been very helpful. Feel free to close this if you want.
